### ISSUE TITLE
Add calculation of Effective Interest Rates

### ISSUE THREAD

**Issue by r0cketr1kky** [tk3369/NPFinancial.jl#2]
Effective Interest rate(ieff) = ((1 + (r/(C*K)))^C - 1) * 100
where r is the nominal rate
K is the number of payments per year
C is the number of Compounding periods per payment period

**Comment by r0cketr1kky** [comment]
Can you assign me this task @tk3369 ?

**Comment by tk3369** [comment]
My original intent is to replicate the exact functionality from numpy.  However, I do not mind adding more functions above and beyond that ;-)

@r0cketr1kky  Feel free to submit a PR

**Comment by r0cketr1kky** [comment]
Sorry for the late response. Thank you @tk3369

**Comment by tk3369** [comment]
Hi @r0cketr1kky.  Sorry, I haven't paid much attention to the math before but now that I'm looking at your PR, it seems to be off.  As far as I know, the effective interest rate is calculated as:

effective interest rate = (1 + r / n) ^ n - 1

where 
- r = nominal rate (annual)
- n = number of compounding periods

As an example, the effective interest rate of for a 10% nominal rate compounding monthly would be (1 + 0.1 / 12) ^ 12 - 1, which is 0.1047 (or 10.47%).

It seems that my `n` is the same as `C * K` in your formula above.  However, your exponent is only `C`.  So that appears to be an error.  If you think it's incorrect, please explain and perhaps give me a reference.

As far as implementation goes, I will provide additional feedbacks at the PR.

**Comment by r0cketr1kky** [comment]
Yes, you're right @tk3369 . If I took the effective interest rate per payment period, it would be `C * K` else it would be just `C`. I'll correct it right away.
Thank you for pointing this out :)

**Comment by tk3369** [comment]
Already fixed and merged... closing issue.
